version: '3.4'

services:
  clientapp:
    image: clientapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes: 
      - .:/home/client-app 
networks:
  default:
    external: true
    name: app-network
